const emblems = [
    {
        name: "Marth",
        line: "Main line",
        imageSrc: "images/emblems/Marth_200Thumb.jpg",
        imageAlt: "Marth",  
        description: "The Ring of the Hero-King enables to wearer to wield Marth's power in combat. When the twelve Emblem Rings were divided amongst the nations of Elyos, the Ring of the Hero-King was one of the six that was retained by Lythos. While her child slept, Lumera placed the ring on Alears hand, allowing them to bond with the Ring as Marth patiently watched them over the millennium. After a thousand years, Alear suddenly awakens and is brought to Lythos Castle shortly afterwards. To help Alear fully acclimate, Lumera has a sparring session with them and encourages Alear to see if they can awaken the power of the Ring of the Hero-King. Alear suddenly hears an incantation in their mind and recites it, causing the Ring to awaken. Alear would take the Ring of the Hero-King on their journey.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Perceptive</b></td>",
                      "<td>Skill(Inheritable)</td>",
                      "<td>If the unit initiates combat, grants Avo+15 during combat. Avo increases with high Spd. SP Cost: 250</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Avoid +10</b></td>",
                      "<td>Skill(Inheritable)</td>",
                      "<td>Grants Avo+10. SP Cost: 500</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Divine Speed</b></td>",
                      "<td>Skill(Engage Skill)</td>",
                      "<td>Unit performs an extra attack at 50% damage in combat.",
                        "<table>",
                            "<tr>",
                                "<td><b>[Dragon]</b> Unit recovers HP equal to damage dealt by extra attack.</td>",
                            "</tr>",
                            "<tr>",
                                "<td><b>[Covert]</b> If extra attack hits, poisons foe.</td>",
                            "</tr>",
                        "</table>",
                      "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Lodestar Rush</b></td>",
                        "<td>Skill(Engage Attack)</td>",
                        "<td>Use to launch 7 consecutive sword attacks at 30% damage. Adjacent foe only.",
                            "<table>",
                                "<tr>",
                                    "<td><b>[Dragon]</b> +2 attacks.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Backup]</b> +1 attack.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Mystical]</b> Damage based on their Magic stat.</td>",
                                "</tr>",
                            "</table>",
                        "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Rapier</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Sword wielded by Emblem Marth. Effective: Cavalry, Armored.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>2</td>",
                        "<td><b>Sword Agility 1</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+10 at a cost of Crit-10 when using a sword. SP Cost: 500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>3</td>",
                        "<td><b>Break Defenses</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>If unit's attack breaks foe, unit makes an extra attack at 50% damage. SP Cost: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>4</td>",
                        "<td><b>Avoid +15</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+15. SP Cost: 1500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>5</td>",
                        "<td>Skill Inheritance</td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit can inherit this Emblem's Skills</td>",
                    "</tr>",
                    "<tr>",
                        "<td>6</td>",
                        "<td><b>Sword Agility 2</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+15 at a cost of Crit-10 when using a sword. SP Cost: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>7</td>",
                        "<td><b>Unyielding</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>At start of player phase, if HP is 20% or less, restores 20% of unit's max HP. SP Cost: 100</td>",
                    "</tr>",
                    "<tr>",
                        "<td>8</td>",
                        "<td><b>Sword Agility 3</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+20 at a cost of Crit-10 when using a sword.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>8</td>",
                       " <td><b>Sword Prof.</b></td>",
                        "<td>Proficiency(Sword)</td>",
                        "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>9</td>",
                        "<td><b>Avoid +20</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+20. <b>SP Cost</b>: 2500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>10</td>",
                        "<td><b>Mercurius</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Sword wielded by Emblem Marth. Doubles user's earned experience.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>11</td>",
                        "<td><b>Strong Bond</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit stays engaged 1 additional turn.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>12</td>",
                        "<td><b>Unyielding+</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>At start of player phase, if HP is 30% or less, restores 30% of unit's max HP. <b>SP Cost</b>: 200</td>",
                    "</tr>",
                    "<tr>",
                        "<td>13</td>",
                        "<td><b>Sword Agility 4</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+25 at a cost of Crit-10 when using a sword. <b>SP Cost</b>: 3000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>14</td>",
                        "<td><b>Avoid +25</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+25. <b>SP Cost</b>: 3500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>15</td>",
                        "<td><b>Falchion</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Sacred sword wielded by Emblem Marth. Effective: Dragon.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>16</td>",
                        "<td><b>Perceptive+</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>If the unit initiates combat, grants Avo+30 during combat. Avo increases with high Spd. <b>SP Cost</b>: 500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>17</td>",
                        "<td><b>Sword Agility 5</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+30 at a cost of Crit-10 when using a sword. <b>SP Cost</b>: 4000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>18</td>",
                        "<td><b>Unyielding++</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>At start of player phase, if HP is 40% or less, restores 40% of unit's max HP. <b>SP Cost</b>: 300</td>",
                    "</tr>",
                    "<tr>",
                        "<td>19</td>",
                        "<td><b>Avoid +30</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Avo+30. <b>SP Cost</b>: 4500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>20</td>",
                        "<td><b>Deep Synergy</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit's engage meter is shortened one step</td>",
                    "</tr>",                    
        ],
    },
    {
        name: "Sigurd",
        line: "Main line",
        imageSrc: "images/emblems/Sigurd_200Thumb.jpg",
        imageAlt: "Sigurd",
        description: "The Ring of the Holy Knight enables to wearer to wield Sigurd's power in combat. When the Emblem Rings were distributed throughout Elyos, the Ring of the Holy Knight was among the six retained by Lythos. When Alear awoke 1000 years after the rings were distributed, Queen Lumera brought Alear to Lythos Castle and decided to train them in combat in hopes of reawakening their memories. Using the Ring of the Holy Knight for their sparring match, she was ultimately unsuccessful in helping them remember their lost memories.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Canter</b></td>",
                      "<td>Skill(Inheritable)</td>",
                      "<td>Unit can move 2 spaces after acting. <b>SP Cost</b>: 1000</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Hit +10</b></td>",
                      "<td>Skill(Inheritable)</td>",
                      "<td>Grants Hit+10. <b>SP Cost</b>: 500</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Gallop</b></td>",
                      "<td>Skill(Engage Skill)</td>",
                      "<td>Grants Mov+5",
                        "<table>",
                            "<tr>",
                               "<td><b>[Cavalry]</b> Move +2.</td>",
                            "</tr>",
                            "<tr>",
                                "<td><b>[Covert]</b> Unit does not pay extra movement cost on any terrain.</td>",
                            "</tr>",
                            "<tr>",
                                "<td><b>[Dragon]</b> Grants another Mov +1.</td>",
                            "</tr>",
                        "</table>",
                      "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Override</b></td>",
                        "<td>Skill(Engage Attack)</td>",
                        "<td>Use to attack and move through a line of adjacent foes. Sword/lance only.",
                            "<table>",
                                "<tr>",
                                    "<td><b>[Dragon]</b> +20% Damage.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Mystical]</b> Deals extra damage=25% of Mag.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Qi Adept]</b> 20% chance of breaking target.</td>",
                                "</tr>",
                            "</table>",
                        "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Ridersbane</b></td>",
                        "<td>Weapon</td>",
                        "<td>Lance wielded by Emblem Sigurd. Effective: Cavalry. (Purchase regular Ridersbane for 2500G)</td>",
                    "</tr>",
                    "<tr>",
                        "<td>2</td>",
                        "<td><b>Lance Power</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+2 at a cost of Avo-10 when using a lance. <b>SP Cost</b>: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>3</td>",
                        "<td><b>Momentum</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+1 to first attack during combat for each space unit moved before attacking (Max +10). <b>SP Cost</b>: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>4</td>",
                        "<td><b>Hit +15</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+15. SP Cost: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>5</td>",
                        "<td>Skill Inheritance</td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit can inherit this Emblem's Skills</td>",
                    "</tr>",
                    "<tr>",
                        "<td>6</td>",
                        "<td><b>Lance Power 2</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+4 at a cost of Avo-10 when using a lance. <b>SP Cost</b>: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>6</td>",
                        "<td><b>Lance Prof.</b></td>",
                        "<td>Proficiency(Lance)</td>",
                        "<td>Proficiency with lances. Required for promotion to certain classes.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>7</td>",
                        "<td><b>Headlong Rush</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants immunity to freeze. <b>SP Cost</b>: 200</td>",
                    "</tr>",
                    "<tr>",
                        "<td>8</td>",
                        "<td><b>Lance Power 3</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+6 at a cost of Avo-10 when using a lance. <b>SP Cost</b>: 3000</td>",
                    "</tr>",
                   "<tr>",
                        "<td>9</td>",
                        "<td><b>Sword Prof.</b></td>",
                        "<td>Proficiency(Sword)</td>",
                        "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>10</td>",
                        "<td><b>Brave Lance</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Lance wielded by Emblem Sigurd. If user initiates combat, attacks twice.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>11</td>",
                        "<td><b>Strong Bond</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit stays engaged 1 additional turn.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>12</td>",
                        "<td><b>Hit +20</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit +20 <b>SP Cost</b>: 1500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>13</td>",
                        "<td><b>Canter +</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Unit can move 3 spaces after acting. <b>SP Cost</b>: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>14</td>",
                        "<td><b>Lance Power 4</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+8 at a cost of Avo-10 when using a lance. <b>SP Cost</b>: 4000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>15</td>",
                        "<td><b>Tyrfing</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Sword wielded by Emblem Sigurd.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>16</td>",
                        "<td><b>Hit +25</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit +25 <b>SP Cost</b>: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>17</td>",
                        "<td><b>Momentum +</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+1 to first attack during combat for each space unit moved before attacking. <b>SP Cost</b>: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>18</td>",
                        "<td><b>Lance Power 5</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Atk+10 at a cost of Avo-10 when using a lance. <b>SP Cost</b>: 5000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>19</td>",
                        "<td><b>Hit +30</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+30. <b>SP Cost</b>: 2500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>20</td>",
                        "<td><b>Deep Synergy</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit's engage meter is shortened one step</td>",
                    "</tr>"
        ]
    },
    {
        name: "Celica",
        line: "Main line",
        imageSrc: "images/emblems/Celica_200Thumb.jpg",
        imageAlt: "Celica",
        description: "In Elyos, Emblem Celica is one of the twelve Emblems that protect the continent. In the aftermath of the war against the Fell Dragon Sombron, Celica's ring, the Ring of the Caring Princess, was entrusted to the kingdom of Firene. In Chapter 4, Elusia begins its invasion of Firene to steal Firene's Emblem Ring. Queen Ève entrusts the Ring of the Caring Princess to her daughter, Princess Céline, to deliver to the Divine Dragon Alear who had arrived in Firene with Prince Alfred. Céline meets with Alear and Alfred's forces in Florra Mill Town and hands the Ring of the Caring Princess to Alear, allowing them to evoke the ring, restoring Celica's powers. Alear gives the Ring back to Céline to use in the immediate battle against the Elusian forces that were tailing her.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
          "<tr>",
            "<td>1</td>",
            "<td><b>Magic +2</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>Grants Mag+2 <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Holy Stance</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>If a Corrupted attacks unit, deals 10% of damage take back to foe. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Echo</b></td>",
            "<td>Skill(Engage Skill)</td>",
            "<td>Use to attack with magic at 50% damage. Use a second time to launch another 50% attack.",
              "<table>",
                  "<tr>",
                      "<td><b>[Mystical]</b> +10% damage.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Dragon]</b> Range +1.</td>",
                  "</tr>",
              "</table>",
            "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Warp Ragnarok</b></td>",
              "<td>Skill(Engage Attack)</td>",
              "<td>Use to warp up to 10 spaces and make a powerful magic attack.",
                  "<table>",
                      "<tr>",
                          "<td><b>[Dragon]</b> Attack range +1.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Mystical]</b> +20% damage.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Cavalry]</b> Warp distance +2.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Flying]</b> Warp distance +5.</td>",
                      "</tr>",
                  "</table>",
              "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Seraphim</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Holy tome wielded by Emblem Celica. Effective: Corrupted.</td>",
          "</tr>",
          "<tr>",
              "<td>2</td>",
              "<td><b>Magic +3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Mag+3. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Resonance</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>When equipped with a tome, if unit's HP is 2 or more, unit loses 1 HP at start of combat and deals +2 damage during combat. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Tome Precision 1</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+3 when using a tome. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
              "<td>5</td>",
              "<td>Skill Inheritance</td>",
              "<td>Bond Bonus</td>",
              "<td>Unit can inherit this Emblem's Skills</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Tome Prof.</b></td>",
              "<td>Proficiency(Magic)</td>",
              "<td>Proficiency with magic. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Tome Precision 2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+5 when using a tome. <b>SP Cost</b>: 300</td>",
          "</tr>",
          "<tr>",
              "<td>8</td>",
              "<td><b>Favorite Food</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>When unit eats a packed lunch, its engage meter is maxed out. <b>SP Cost</b>: 200</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Tome Precision 3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+7 when using a tome. <b>SP Cost</b>: 700</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Sword Prof.</b></td>",
              "<td>Proficiency(Sword)</td>",
              "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>10</td>",
              "<td><b>Recover</b></td>",
              "<td>Weapon</td>",
              "<td>Staff wielded by Emblem Celica. Rcovers a great deal of HP. (Purchase regular Recover for 3000G)</td>",
          "</tr>",
          "<tr>",
              "<td>11</td>",
              "<td><b>Strong Bond</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit stays engaged 1 additional turn.</td>",
          "</tr>",
          "<tr>",
              "<td>12</td>",
              "<td><b>Holy Stance +</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If a Corrupted attacks unit, deals 30% of damage taken back to foe. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>13</td>",
              "<td><b>Magic +4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Mag+4. <b>SP Cost</b>: 4000</td>",
          "</tr>",
          "<tr>",
              "<td>14</td>",
              "<td><b>Tome Precision 4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+10 when using a tome. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>15</td>",
              "<td><b>Ragnarok</b></td>",
              "<td>Weapon(Synchro Skill)</td>",
              "<td>Mighty fire tome wielded by Emblem Celica.</td>",
          "</tr>",
          "<tr>",
              "<td>16</td>",
              "<td><b>Resonance +</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>When equipped with a tome, if unit's HP is 2 or more, unit loses 1 HP at start of combat and deals +3 damage during combat. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>17</td>",
              "<td><b>Tome Precision 5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+15 when using a tome. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>18</td>",
              "<td><b>Holy Stance ++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If a Corrupted attacks unit, deals 50% of damage taken back to foe. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>19</td>",
              "<td><b>Magic +5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Mag+5. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>20</td>",
              "<td><b>Deep Synergy</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit's engage meter is shortened one step</td>",
          "</tr>"
        ]
    },
    {
        name: "Micaiah",
        line: "Main line",
        imageSrc: "images/emblems/Micaiah_200Thumb.jpg",
        imageAlt: "Micahiah",
        description: "The Ring of the Dawn Maiden houses the spirit of Micaiah from Fire Emblem: Radiant Dawn. When the Emblem Rings were distributed, each kingdom received one of the rings. However, Firene actually held two rings. It was widely known that they held the Ring of the Caring Princess, however the Ring of the Dawn Maiden was also entrusted to them. They hid the ring in a shrine near their border with Brodia.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Resistance +2</b></td>",
                      "<td>Skill(Inheritable)</td>",
                      "<td>Grants Res+2. <b>SP Cost</b>: 300</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Cleric</b></td>",
                      "<td>Skill(Synchro Skill)</td>",
                      "<td>Unit can equip staves up to level C.</td>",
                    "</tr>",
                    "<tr>",
                      "<td>1</td>",
                      "<td><b>Augment</b></td>",
                      "<td>Skill(Engage Skill)</td>",
                      "<td>Grants staff range +5 and area of effect +1.",
                        "<table>",
                            "<tr>",
                                "<td><b>[Qi Adept]</b> 20% to HP healed by staves.</td>",
                            "</tr>",
                            "<tr>",
                                "<td><b>[Dragon]</b> Additional staff range +5 and area of effect +1.</td>",
                            "</tr>",
                        "</table>",
                      "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Great Sacrifice</b></td>",
                        "<td>Skill(Engage Attack)</td>",
                        "<td>Use to restore HP to all allies, even to those ont under the players control. After use, unit's HP=1.",
                            "<table>",
                                "<tr>",
                                    "<td><b>[Dragon]</b> After use, unit's HP=30%.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Armored]</b> Grants Def+1 to all healed during their next combat.</td>",
                                "</tr>",
                                "<tr>",
                                    "<td><b>[Qi Adept]</b> Also cures status effects.</td>",
                                "</tr>",
                            "</table>",
                        "</td>",
                    "</tr>",
                    "<tr>",
                        "<td>1</td>",
                        "<td><b>Shine</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Light tome wielded by Emblem Micaiah. Illuminates a 5-space radius (Shrinks one space per turn).</td>",
                    "</tr>",
                    "<tr>",
                        "<td>2</td>",
                        "<td><b>Staff Mastery 1</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+10 when using a staff. Staves also heal and additional 3 HP. <b>SP Cost</b>: 100</td>",
                    "</tr>",
                    "<tr>",
                        "<td>3</td>",
                        "<td><b>Healing Light</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>When unit heals an ally with a staff, unit also recovers HP=50% of the amount healed. <b>SP Cost</b>: 200</td>",
                    "</tr>",
                    "<tr>",
                        "<td>3</td>",
                        "<td><b>Staff Prof.</b></td>",
                        "<td>Proficiency(Staff)</td>",
                        "<td>Proficiency with staves. Required for promotion to certain classes.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>4</td>",
                        "<td><b>Resistance +3</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Res+3. SP Cost: 500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>5</td>",
                        "<td>Skill Inheritance</td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit can inherit this Emblem's Skills</td>",
                    "</tr>",
                    "<tr>",
                        "<td>6</td>",
                        "<td><b>Knife Prof.</b></td>",
                        "<td>Proficiency(Knife)</td>",
                        "<td>Proficiency with knives. Required for promotion to certain classes.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>7</td>",
                        "<td><b>Silence Ward</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants immunity to silence. <b>SP Cost</b>: 200</td>",
                    "</tr>",
                    "<tr>",
                        "<td>8</td>",
                        "<td><b>Staff Mastery 2</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+15 when using a staff. Staves also heal an additional 5 HP. <b>SP Cost</b>: 300</td>",
                    "</tr>",
                    "<tr>",
                        "<td>9</td>",
                        "<td><b>Magic Prof.</b></td>",
                        "<td>Proficiency(Magic)</td>",
                        "<td>Proficiency with magic. Required for promotion to certain classes.</td>",
                    "</tr>",        
                    "<tr>",
                        "<td>10</td>",
                        "<td><b>Nosferatu</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Light tome wielded by Emblem Micaiah. User recovers HP equal to 50% of damage dealt.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>11</td>",
                        "<td><b>Strong Bond</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit stays engaged 1 additional turn.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>12</td>",
                        "<td><b>Staff Mastery 3</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+20 when using a staff. Staves also heal an additional 7 HP. <b>SP Cost</b>: 500</td>",
                    "</tr>",
                    "<tr>",
                        "<td>13</td>",
                        "<td><b>Cleric +</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Unit can equip staves up to level B.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>14</td>",
                        "<td><b>Resistance +4</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Res +4. <b>SP Cost</b>: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>15</td>",
                        "<td><b>Thani</b></td>",
                        "<td>Weapon(Exclusive)</td>",
                        "<td>Mighty light tome wielded by Emblem Micaiah. Effective: Cavalry, Armored.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>16</td>",
                        "<td><b>Staff Mastery 4</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+25 when using a staff. Staves also heal an additional 10 HP. <b>SP Cost</b>: 700</td>",
                    "</tr>",
                    "<tr>",
                        "<td>17</td>",
                        "<td><b>Staff Mastery</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Hit+30 when using a staff. Staves also heal an additional 15 HP. <b>SP Cost</b>: 1000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>18</td>",
                        "<td><b>Cleric ++</b></td>",
                        "<td>Skill</td>",
                        "<td>Unit can equip staves up to level A.</td>",
                    "</tr>",
                    "<tr>",
                        "<td>19</td>",
                        "<td><b>Resistance +5</b></td>",
                        "<td>Skill(Inheritable)</td>",
                        "<td>Grants Res+5. <b>SP Cost</b>: 2000</td>",
                    "</tr>",
                    "<tr>",
                        "<td>20</td>",
                        "<td><b>Deep Synergy</b></td>",
                        "<td>Bond Bonus</td>",
                        "<td>Unit's engage meter is shortened one step</td>",
                    "</tr>"

        ]
    },
    {
        name: "Leif",
        line: "Main line",
        imageSrc: "images/emblems/Leif_200Thumb.jpg",
        imageAlt: "Leif",
        description: "The Ring of the Sage Lord houses the Emblem spirit of Leif from Fire Emblem: Thracia 776. It was one of the six rings still held by Lythos when the rings were distributed throughout Elyos. When Elusia raided the Ring Vault of Lythos, it was one of the rings that was stolen. Princess Ivy was tasked with sieging Brodia Castle by King Hyacinth. To aid her, he gave her the Ring of the Sage Lord which had been corrupted by Sombron. After a grueling battle, Ivy is defeated allowing Alear to recover the Ring and purify it.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
          "<tr>",
            "<td>1</td>",
            "<td><b>Arms Shield</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>When unit hsa weapon advantage, that unit takes 3 less damage. <b>SP Cost</b>: 200</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Adaptable</b></td>",
            "<td>Skill(Engage Skill)</td>",
            "<td>If foe initiates combat, unit counters with the best weapon available (in terms of range, weapon advantage, effective bonus, etc.).",
              "<table>",
                  "<tr>",
                      "<td><b>[Armored]</b> Def+5 during combat.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Covert]</b> Avo+20 during combat.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Dragon]</b> Hit+30 during combat.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Backup]</b> Crit+10 during combat.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Flying]</b> Res+5 during combat.</td>",
                  "</tr>",
              "</table>",
            "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Quadruple Hit</b></td>",
              "<td>Skill(Engage Attack)</td>",
              "<td>Use to attack once each with sword, lance, axe, and bow.",
                  "<table>",
                      "<tr>",
                          "<td><b>[Dragon]</b> +20 damage.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Covert]</b> Foes may drop 1,000G. Trigger %=Lck.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Qi Adept]</b> Breaks foes.</td>",
                      "</tr>",
                  "</table>",
              "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Killer Axe</b></td>",
              "<td>Weapon</td>",
              "<td>Axe wielded by Emblem Leif. Easily inflicts fatal wounds. (Purchase regular Killer Axe for 3000G)</td>",
          "</tr>",
          "<tr>",
              "<td>2</td>",
              "<td><b>Axe Prof.</b></td>",
              "<td>Proficiency(Axe)</td>",
              "<td>Proficiency with axes. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Bow Prof.</b></td>",
              "<td>Proficiency(Bow)</td>",
              "<td>Proficiency with bows. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Vantage</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit's HP is 25% or less and foe initiates combat, unit can counter before foe's first attack. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Knife Precision 1</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+3 when using a knife. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Knife Prof.</b></td>",
              "<td>Proficiency(Knife)</td>",
              "<td>Proficiency with knives. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>5</td>",
              "<td><b>Skill Inheritance</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit can inherit this Emblem's Skills</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Build +4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Bld+4. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Staff Prof.</b></td>",
              "<td>Proficiency(Staff)</td>",
              "<td>Proficiency with staves. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Arms Shield+</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>When unit has weapon advantage, unit takes 5 less damage. <b>SP Cost</b>: 400</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Lance Prof.</b></td>",
              "<td>Proficiency(Lance)</td>",
              "<td>Proficiency with lances. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>8</td>",
              "<td><b>Sword Prof.</b></td>",
              "<td>Proficiency(Lance)</td>",
              "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Knife Precision 2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+6 when using a knife. <b>SP Cost</b>: 300</td>",
          "</tr>",
          "<tr>",
              "<td>10</td>",
              "<td><b>Master Lance</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Lance wielded by Emblem Leif. If user initiates combat, attacks twice. Can strike close or at range.</td>",
          "</tr>",
          "<tr>",
              "<td>11</td>",
              "<td><b>Strong Bond</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit stays engaged 1 additional turn.</td>",
          "</tr>",
          "<tr>",
              "<td>12</td>",
              "<td><b>Vantage +</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit's HP is 50% or less and foe initiates combat, unit can counter before foe's first attack. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>13</td>",
              "<td><b>Knife Precision 3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+7 when using a knife. <b>SP Cost</b>: 700</td>",
          "</tr>",
          "<tr>",
              "<td>14</td>",
              "<td><b>Build +5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Bld+5. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>15</td>",
              "<td><b>Light Brand</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Magical sword wielded by Emblem Leif. Grants Lck+10. Can strick close or at range</td>",
          "</tr>",
          "<tr>",
              "<td>16</td>",
              "<td><b>Arms Shield ++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>When unit has weapon advantage, unit takes 7 less damage <b>SP Cost</b>: 600</td>",
          "</tr>",
          "<tr>",
              "<td>17</td>",
              "<td><b>Knife Precision 4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+10 when using a knife. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>18</td>",
              "<td><b>Vantage ++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit's HP is 75% or less and foe initiates combat, unit can counter before foe's first attack. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>19</td>",
              "<td><b>Knife Precision 5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit/Avo+15 when using a knife. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>20</td>",
              "<td><b>Deep Synergy</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit's engage meter is shortened one step</td>",
          "</tr>"

        ]
    },
    {
        name: "Roy",
        line: "Main line",
        imageSrc: "images/emblems/Roy_200Thumb.jpg",
        imageAlt: "Roy",
        description: "The Ring of the Young Lion was safeguarded by the Kingdom of Brodia. Upon the arrival of Alear to Brodia, King Morion personally brought the ring immediately to them. The Ring of the Young Lion enables the wearer to wield Roy's power in combat.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
          "<tr>",
            "<td>1</td>",
            "<td><b>Strength +1</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>Grants Str+1. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Hold Out</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>If Unit had 30% HP or more at start of combat, unit always survives combat with at least 1 HP. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Rise Above</b></td>",
            "<td>Skill(Engage Skill)</td>",
            "<td>Grants Lvl+5",
              "<table>",
                  "<tr>",
                      "<td><b>[Cavalry]</b> Move +1.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Armored]</b> Max HP+5.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Dragon]</b> Additional Lvl+1.</td>",
                  "</tr>",
              "</table>",
            "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Blazing Lion</b></td>",
              "<td>Skill(Engage Attack)</td>",
              "<td>Use to attack adjacent foe and an area 3 spaces wide. Target area and the 2 rows beyond it are set on fire. Sword only.",
                  "<table>",
                      "<tr>",
                          "<td><b>[Dragon]</b> Attack range +3 spaces.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Mystical]</b> Expands flames area.</td>",
                      "</tr>",
                  "</table>",
              "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Lancereaver</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Unusual sword wielded by Emblem Roy. Grants advatage vs. lances but disadvantage vs. axes.</td>",
          "</tr>",
          "<tr>",
              "<td>2</td>",
              "<td><b>Strength +2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Str+2. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Advance</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Use to move 1 space tward a foe that is 2 spaces away and attack. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Sword Power 1</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Atk+2 at a cost of Avo-10 when using a sword. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>5</td>",
              "<td>Skill Inheritance</td>",
              "<td>Bond Bonus</td>",
              "<td>Unit can inherit this Emblem's Skills</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Sword Prof.</b></td>",
              "<td>Proficiency(Sword)</td>",
              "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Sword Power 2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Atk+4 at a cost of Avo-10 when using a sword. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>8</td>",
              "<td><b>Hold Out+</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If Unit had 20% HP or more at start of combat, unit always survives combat with at least 1 HP. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Strength +3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Str+3. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Sword Power 3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Atk+6 at a cost of Avo-10 when using a sword. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>10</td>",
              "<td><b>Wyrmslayer</b></td>",
              "<td>Weapon</td>",
              "<td>Sword wielded by Emblem Roy. Effective: Dragon. (Purchase regular Wyrmslayer for 2500G)</td>",
          "</tr>",
          "<tr>",
              "<td>11</td>",
              "<td><b>Strong Bond</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit stays engaged 1 additional turn.</td>",
          "</tr>",
          "<tr>",
              "<td>12</td>",
              "<td><b>Sword Power 4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Atk+8 at a cost of Avo-10 when using a sword. <b>SP Cost</b>: 4000</td>",
          "</tr>",
          "<tr>",
              "<td>13</td>",
              "<td><b>Hold Out ++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit had 10% HP or more at start of combat, unit always survives combat with at least 1 HP. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>14</td>",
              "<td><b>Strength +4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Str+4. <b>SP Cost</b>: 4000</td>",
          "</tr>",
          "<tr>",
              "<td>15</td>",
              "<td><b>Binding Blade</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Famous sword wielded by Emblem Roy. Grants Def/Res+5. Can strike clse or at range.</td>",
          "</tr>",
          "<tr>",
              "<td>16</td>",
              "<td><b>Sword Power 5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Atk+10 at a cost of Avo-10 when using a sword. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>17</td>",
              "<td><b>Strength +5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Str+5. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>18</td>",
              "<td><b>Hold Out +++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit had 2 HP or more at start of combat, unit always survives combat with at least 1 HP. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>19</td>",
              "<td><b>Strength +6</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Str+6. <b>SP Cost</b>: 5000</td>",
          "</tr>",
          "<tr>",
              "<td>20</td>",
              "<td><b>Deep Synergy</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit's engage meter is shortened one step</td>",
          "</tr>"

        ]
    },
    {
        name: "Lyn",
        line: "Main line",
        imageSrc: "images/emblems/Lyn_200Thumb.jpg",
        imageAlt: "Lyn",
        description: "The Ring of the Lady of the Plains enables the wearer to wield Lyn's power in combat. When the 12 Emblem Rings were distributed to the kingdoms of Elyos, Elusia was given the Ring of the Lady of the Plains to safeguard. Having allied themselves with the Fell Dragon Sombron, King Hyacinth gave the ring to Sombron so the ring could be corrupted. Hyacinth sent a challenge to King Morion of Brodia to face him in combat. Blinded by his sense of honor, Morion accepted his challenge and faced him just outside the Fort on the Border between Brodia and Elusia. The two dueled with Morion quickly gaining the upper hand, forcing Hyacinth to utilize the corrupted Ring of the Lady of the Plains, subduing Morion enough to take him to Elusia so he could use Morion's sovereign blood to revive Sombron. Upon Sombron's revival and the subsequent theft of the Emblem Rings in Alear's possession, Princess Ivy stole the Ring of the Lady of the Plains and delivered it alongside the Ring of the Princess Exalt in the Shadowy Moor as they escaped Elusia into Solm. Alear was able to then purify the Rings and escape successfully.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
          "<tr>",
            "<td>1</td>",
            "<td><b>Speed +1</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>Grants Spd+1. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Alacrity</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>If unit initiates combat with a Spd advantage of 9 or more, unit's follow-up (if possible) occurs before foe can counterattack. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Call Doubles</b></td>",
            "<td>Skill(Engage Skill)</td>",
            "<td>Creates four illusory doubles that can make chain attacks with unit.",
              "<table>",
                  "<tr>",
                      "<td><b>[Flying]</b> Doubles have +10 Avo</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Dragon]</b> +1 double created.</td>",
                  "</tr>",
              "</table>",
            "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Astra Storm</b></td>",
              "<td>Skill(Engage Attack)</td>",
              "<td>Use to launch 5 bow attacks at 30% damage, up to range 10.",
                  "<table>",
                      "<tr>",
                          "<td><b>[Dragon]</b> Range +5.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Covert]</b> Range +10.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Qi Adept]</b> Breaks the target.</td>",
                      "</tr>",
                  "</table>",
              "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Killer Bow</b></td>",
              "<td>Weapon</td>",
              "<td>Bow wielded by Emblem Lyn. Easily inflicts fatal wounds. (Purchase regular Killer Bow for 3000G)</td>",
          "</tr>",
          "<tr>",
              "<td>2</td>",
              "<td><b>Speed +2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Spd+2. <b>SP Cost</b>: 300</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Speedtaker</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants a stacking Spd+2 each time unit initiates combat and defeats a foe. Bonus lasts for the rest of the battle. (Max +10). <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Bow Focus</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit+10 at a cost of Ddg-10 when using a bow. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
              "<td>5</td>",
              "<td>Skill Inheritance</td>",
              "<td>Bond Bonus</td>",
              "<td>Unit can inherit this Emblem's Skills</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Bow Prof.</b></td>",
              "<td>Proficiency(bow)</td>",
              "<td>Proficiency with Bows. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Bow Focus 2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit+15 at a cost of Ddg-10 when using a bow. <b>SP Cost</b>: 300</td>",
          "</tr>",
          "<tr>",
              "<td>8</td>",
              "<td><b>Sword Prof.</b></td>",
              "<td>Proficiency(Sword)</td>",
              "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Speed +3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Spd+3. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>10</td>",
              "<td><b>Mani Katti</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Divine Sword wielded by Emblem Lyn. Effective: Cavalry, Armored.</td>",
          "</tr>",
          "<tr>",
              "<td>11</td>",
              "<td><b>Strong Bond</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit stays engaged 1 additional turn.</td>",
          "</tr>",
          "<tr>",
              "<td>12</td>",
              "<td><b>Bow Focus 3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit+20 at a cost of Ddg-10 when using a bow. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>13</td>",
              "<td><b>Alacrity +</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit initiates combat with a Spd advantage of 7 or more, unit's follow up (if possible) occurs before foe can counterattack. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>14</td>",
              "<td><b>Bow Focus 4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit+25 at a cost of Ddg-10 when using a bow. <b>SP Cost</b>: 7000</td>",
          "</tr>",
          "<tr>",
              "<td>15</td>",
              "<td><b>Mulagir</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Mighty bow wielded by Emblem Lyn. Grants Spd+5. Effective: Flying, Dragon.</td>",
          "</tr>",
          "<tr>",
              "<td>16</td>",
              "<td><b>Speed +4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Spd+4 <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>17</td>",
              "<td><b>Bow Focus 5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Hit+30 at a cost of Ddg-10 when using a bow. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>18</td>",
              "<td><b>Alacrity ++</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit initiates combat with a Spd advantage of 5 or more, unit's follow up (if possible) occurs before foe can counterattack. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>19</td>",
              "<td><b>Speed +5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Spd+5. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>20</td>",
              "<td><b>Deep Synergy</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit's engage meter is shortened one step</td>",
          "</tr>"
        ]
    },
    {
        name: "Lucina",
        line: "Main line",
        imageSrc: "images/emblems/Lucina_200Thumb.jpg",
        imageAlt: "Lucina",
        description: "The Ring of the Princess Exalt enables to wearer to wield Lucina's power in combat. During the raid of Lythos by Gradlon, the Ring of the Princess Exalt was stolen. Sombron was able to awaken the ring and corrupted it, bequeating it to the kingdom of Elusia. During Chapter 7, Princess Hortensia wielded the ring against Alear and their forces. At some point between Chapter 9 and Chapter 11, Ivy managed to acquire the ring, alongside Ring of the Lady of the Plains, and delivered them to Alear at the Shadowy Moor whom successfully purified them.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [
          "<tr>",
            "<td>1</td>",
            "<td><b>Dexterity +1</b></td>",
            "<td>Skill(Inheritable)</td>",
            "<td>Grants Dex+1. <b>SP Cost</b>: 100</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Dual Strike</b></td>",
            "<td>Skill</td>",
            "<td>Unit participates in chain attacks as if it were a backup unit.</td>",
          "</tr>",
          "<tr>",
            "<td>1</td>",
            "<td><b>Bonded Shield</b></td>",
            "<td>Skill(Engage Skill)</td>",
            "<td>Use to prevent first attacks on adjacent allies until your next turn. Trigger %=80.",
              "<table>",
                  "<tr>",
                      "<td><b>[Cavalry]</b> Trigger %= 100 for Cavalry allies.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Armored]</b> Trigger %=100 for armored allies.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Dragon]</b> +10% to trigger rate.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Flying]</b> Trigger %=100 for Flying allies.</td>",
                  "</tr>",
                  "<tr>",
                      "<td><b>[Qi Adept]</b> Trigger %=100</td>",
                  "</tr>",
              "</table>",
            "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>All for One</b></td>",
              "<td>Skill(Engage Attack)</td>",
              "<td>Use to make a sword attack against an adjacent foe. All allies within 2 spaces chain attack.",
                  "<table>",
                      "<tr>",
                          "<td><b>[Dragon]</b> Ally chain attacks are guaranteed to hit.</td>",
                      "</tr>",
                      "<tr>",
                          "<td><b>[Backup]</b> Range +1.</td>",
                      "</tr>",
                  "</table>",
              "</td>",
          "</tr>",
          "<tr>",
              "<td>1</td>",
              "<td><b>Noble Rapier</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Sword wieldd by Emblem Lucina. Effective: Cavalry, Armored.</td>",
          "</tr>",
          "<tr>",
              "<td>2</td>",
              "<td><b>Dexterity +2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Dex+2. <b>SP Cost</b>: 300</td>",
          "</tr>",
          "<tr>",
              "<td>3</td>",
              "<td><b>Dual Assist</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit is able to chain attack, unit will do so when allies attack foes unit could reach by moving. Trigger %=35. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>4</td>",
              "<td><b>Bow Agility 1</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Avo+10 at a cost of Crit-10 when using a bow. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>5</td>",
              "<td>Skill Inheritance</td>",
              "<td>Bond Bonus</td>",
              "<td>Unit can inherit this Emblem's Skills</td>",
          "</tr>",
          "<tr>",
              "<td>6</td>",
              "<td><b>Sword Prof.</b></td>",
              "<td>Proficiency(Sword)</td>",
              "<td>Proficiency with swords. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>7</td>",
              "<td><b>Bow Agility 2</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Avo+15 at a cost of Crit-10 when using a bow. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>8</td>",
              "<td><b>Bow Prof.</b></td>",
              "<td>Proficiency(Bow)</td>",
              "<td>Proficiency with bows. Required for promotion to certain classes.</td>",
          "</tr>",
          "<tr>",
              "<td>9</td>",
              "<td><b>Dexterity +3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Dex+3. <b>SP Cost</b>: 500</td>",
          "</tr>",
          "<tr>",
              "<td>10</td>",
              "<td><b>Parthia</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Bow wielded by Emblem Lucina. Doubles user's earned experience. Grants Res+5. Effective: Flying.</td>",
          "</tr>",
          "<tr>",
              "<td>11</td>",
              "<td><b>Strong Bond</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit stays engaged 1 additional turn.</td>",
          "</tr>",
          "<tr>",
              "<td>12</td>",
              "<td><b>Bow Agility 3</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Avo+20 at a cost of Crit-10 when using a bow. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>13</td>",
              "<td><b>Dual Support</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants a bonus to Avo that increases with unit's support level with adjacent allies. (Max +90) <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>14</td>",
              "<td><b>Bow Agility 4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Avo+25 at a cost of Crit-10 when using a bow. <b>SP Cost</b>: 3000</td>",
          "</tr>",
          "<tr>",
              "<td>15</td>",
              "<td><b>Parallel Falchion</b></td>",
              "<td>Weapon(Exclusive)</td>",
              "<td>Sacred sword wielded by Emblem Lucina. Effective: Dragon.</td>",
          "</tr>",
          "<tr>",
              "<td>16</td>",
              "<td><b>Dexterity +4</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Dex+4. <b>SP Cost</b>: 1000</td>",
          "</tr>",
          "<tr>",
              "<td>17</td>",
              "<td><b>Bow Agility 5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Avo+30 at a cost of Crit-10 when using a bow. <b>SP Cost</b>: 4000</td>",
          "</tr>",
          "<tr>",
              "<td>18</td>",
              "<td><b>Dual Assist +</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>If unit is able to chain attack, unit will do so when allies attack foes unit could reach by moving. Trigger %=70. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>19</td>",
              "<td><b>Dexterity +5</b></td>",
              "<td>Skill(Inheritable)</td>",
              "<td>Grants Dex +5. <b>SP Cost</b>: 2000</td>",
          "</tr>",
          "<tr>",
              "<td>20</td>",
              "<td><b>Deep Synergy</b></td>",
              "<td>Bond Bonus</td>",
              "<td>Unit's engage meter is shortened one step</td>",
          "</tr>"

        ]
    },
    {
        name: "Ike",
        line: "Main line",
        imageSrc: "images/emblems/Ike_200Thumb.jpg",
        imageAlt: "Ike",
        description: "The Ring of the Radiant Hero was given to the Kingdom of Solm when the twelve Emblem Rings were distributed across Elyos. The Ring of the Radiant Hero was known to be safeguarded by the Solm Royal Family itself with Princess Timerra possessing it. The Ring of the Radiant Hero enables the wearer to wield Ike's power in combat.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Byleth",
        line: "Main line",
        imageSrc: "images/emblems/Byleth_200Thumb.jpg",
        imageAlt: "Byleth",
        description: "The Ring of the Instructor is one of the six Emblem Rings originally retained by Lythos when they were were distributed amongst the nations of Elyos following the defeat of Sombron. When Elusia invades Lythos Castle, the Ring of the Instructor is one of the rings stolen from the Ring Vault. Later, when Alear and their forces invade Elusia to rescue King Morion, King Hyacinth gives Princess Hortensia the Ring of the Instructor to fend off the Divine Dragon's forces, though she is ultimately defeated. After Sombron awakens and Ivy betrays the Fell Dragon, Zephia uses Sombron's corruption of the Ring of the Instructor to control Ivy's sister Hortensia, using her as a pawn to invade the Solm royal palace and acquire the Emblem Ring held by the Solmic royal family. After Alear's forces defeat the controlled Hortensia in grueling battle, the princess is freed of the Fell Dragon's influence, and Alear acquires and purifies the Emblem Ring. The Ring of the Instructor is engraved with a pattern evoking Nabatean design, and features coloration based on Byleth's default clothing colors.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Corrin",
        line: "Main line",
        imageSrc: "images/emblems/Corrin_200Thumb.jpg",
        imageAlt: "Corrin",
        description: "The Ring of the Crux of Fate enables the wearer to wield Corrin's power in combat. A thousand years prior to the events of Engage, the Ring of the Crux of Fate was one of the rings distributed across Elyos. It was secretly entrusted to Solm with the general public only knowing that they held the Ring of the Radiant Hero. To keep the Ring of the Crux of Fate safe, the Solm royal family hid it in the Northern Fortress where locals urged people to steer clear of due to rumors of haunted spirits infesting it. Using the rumor, very few dared to venture into the ruins. The Ring of the Crux of Fate bears designs similar to Corrin's armor and the inlet gemstone resembles the design of Corrin's Dragonstone.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Eirika/Ephraim",
        line: "Main line",
        imageSrc: "images/emblems/Erika_200Thumb.jpg",
        imageAlt: "Eirika and Ephraim",
        description: "The Ring of the Azure Twins is one of the six rings in possession of Lythos when the others were distributed throughout the realms. When Elusia invaded Lythos, the Ring of the Azure Twins was one of the four rings stolen during the raid on Lythos Castle. Later, in Chapter 17, Rosado and Goldmary posed as obedient Elusia soldiers in order to steal the Ring of the Azure Twins. They are successful and manage to flee the army in search of Princess Hortensia, eventually reuniting with her at the Azure Coast where she had joined Alear's army. Rosado gives the ring to Alear to awaken Eirika in which Alear gives to Rosado to immediately use in the following battle. The Ring of the Azure Twins enables the wearer to wield Eirika's and Ephraim's power in combat, though conversationally, Eirika is the one who talks to the characters of the game during Bond Supports.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Edelgard/Dimitri/Claide",
        line: "DLC",
        imageSrc: "images/emblems/leaders-profile.jpg",
        imageAlt: "Edelgard, Dimitri, and Claude",
        description: "The Bracelet of the Three Houses is a Bracelet housing the spirits of Edelgard, Dimitri, and Claude. It was discovered by Alear on the Lookout Ridge of the Somniel.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Tiki",
        line: "DLC",
        imageSrc: "images/emblems/EmblemHeadshots_Tiki_DLC_enGB.jpg",
        imageAlt: "Tiki",
        description: "The Bracelet of the Ancestor houses the spirit of Tiki from her Archanea Series appearances as a young girl.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Hector",
        line: "DLC",
        imageSrc: "images/emblems/EHeadshots_Hector_enGB.jpg",
        imageAlt: "Hector",
        description: "The Bracelet of the Brash General houses the spirit of Hector from Fire Emblem: The Blazing Blade.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Soren",
        line: "DLC",
        imageSrc: "images/emblems/EHeadshots_Soren_enGB.jpg",
        imageAlt: "Soren",
        description: "The Bracelet of the Strategist houses the spirit of Soren from Fire Emblem: Path of Radiance and Fire Emblem: Radiant Dawn. According to Soren, his Bracelet was safeguarded by Elusia in an alternative Elyos.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Camilla",
        line: "DLC",
        imageSrc: "images/emblems/EHeadshots_Camille_enGB (1).jpg",
        imageAlt: "Camilla",
        description: "The Bracelet of the Doting Sister houses the spirit of Camilla from Fire Emblem Fates. According to Camilla, her Bracelet was safeguarded by Solm from an alternative version of Elyos.",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Chrom & Robin",
        line: "DLC",
        imageSrc: "images/emblems/chrombin-profile.jpg",
        imageAlt: "Chrom & Robin",
        description: "",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    },
    {
        name: "Veronica",
        line: "DLC",
        imageSrc: "images/emblems/EHeadshots_Veronica_enGB.jpg",
        imageAlt: "Veronica",
        description: "",
        baseLine: [
            "<tr>",
                "<th>Lv.</th>",
                "<th>Bond Effects</th>",
                "<th>Type</th>",
                "<th>Description</th>",
            "</tr>"
        ],
        table: [

        ]
    }
]

export default emblems;  // Export the emblems array as the default export